---
# Depends on ansible.posix
# Install with "ansible-galaxy collection install ansible.posix"
- name: Update Packages
  ansible.builtin.yum:
    name: '*'
    state: latest
- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: latest
- name: Open HTTP Service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
- name: Open HTTPS Service
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled
- name: Reload Firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
- name: Ensure HTTPD Unit is Stopped
  ansible.builtin.systemd:
    name: httpd
    state: stopped
- name: Copy Webserver Site and Configs to Target
  ansible.builtin.copy:
    src: /img/
    dest: /
    force: yes
- name: Start and Enable HTTPD Unit
  ansible.builtin.systemd:
    name: httpd
    enabled: yes
    state: started    
