##########################################
## LOAD BALANCER INFRASTRUCTURE CREATOR ##
##########################################
- name: setup apache
  tags:
   - webServer
  hosts: prod
  remote_user: root
  tasks:
    - include: tasks/updateAll.yml
    - include: tasks/apache.yml

- name: setup balancer
  tags:
   - balancer
  hosts: loadbalancer
  remote_user: root
  tasks:
    - include: tasks/updateAll.yml
    - include: tasks/load_balancer.yml