---

######################################################
# Config Crew Ops Team Monitor Server Setup Playbook #
######################################################

- name: Setup Loadbalancer
  hosts: loadbalancer
  remote_user: root

  tasks:
    # Add the Nginx yum Repository
    - name: Add Repository
      ansible.builtin.yum_repository:
        name: nginx
        description: Nginx Repo
        baseurl: https://nginx.org/packages/centos/7Server/x86_64/
        # Trust Packages Downloaded from this Repo Automatically
        gpgcheck: no

    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
    
    - name: Write the Nginx Config File
      ansible.builtin.template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf

    - name: Write Hosts File
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts

    # - name: Create User
    #   ansible.builtin.user:
    #     name: www-data
    #     state: present

    # - name: Create Logs Dir
    #   ansible.builtin.file:
    #     name: /etc/nginx/logs
    #     state: directory
    #     owner: www-data
    #     group: www-data
    #     mode: 0755
        
    # - name: Create Error Logs
    #   ansible.builtin.file:
    #     name: /etc/nginx/logs/error.log
    #     state: touch
    #     owner: www-data
    #     group: www-data
    #     mode: 0755

    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted