---

######################################################
# Config Crew Ops Team Monitor Server Setup Playbook #
######################################################

# Usage: ansible-playbook loadbalancer_setup.yml

- name: Setup Loadbalancer
  hosts: loadbalancer
  remote_user: root

  tasks:
    # Add the Nginx yum Repository
    - name: Add Repository
      ansible.builtin.yum_repository:
        name: nginx
        description: Nginx Repo
        baseurl: https://nginx.org/packages/centos/7Server/x86_64/
        # Trust Packages Downloaded from this Repo Automatically
        gpgcheck: no

    # Install Nginx on the Loadbalancer
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
    
    # Write nginx.conf J2 Template to Set Up Loadbalancing
    - name: Write the Nginx Config File
      ansible.builtin.template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf

    # Overwrite Loadbalancer Hosts File to that of the Local Machine
    # This is to Allow the Hostnames Pulled from Ansible's Inventory for Web Servers to Function Correctly
    - name: Write Hosts File
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts

    # Ensure Config Changes are Applied and Nginx is Started and Starts on Boot
    - name: Restart and Enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes