---
# Depends on ansible.posix

###########################################################
# Config Crew Ops Team Loadbalancer Server Setup Playbook #
###########################################################

# Usage: ansible-playbook loadbalancer_setup.yml

- name: Setup Loadbalancer
  hosts: loadbalancer
  remote_user: root

  tasks:
    # Add the Nginx yum Repository
    - name: Add Repository
      ansible.builtin.yum_repository:
        name: nginx
        description: Nginx Repo
        baseurl: https://nginx.org/packages/centos/7Server/x86_64/
        # Trust Packages Downloaded from this Repo Automatically
        gpgcheck: no

    # Install Nginx on the Loadbalancer
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
    
    # Write nginx.conf J2 Template to Set Up Loadbalancing
    - name: Write the Nginx Config File
      ansible.builtin.template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf

    # Open HTTP Service then Reload the Firewall
    - name: Open HTTP Service
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Reload Firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded

    # Ensure Config Changes are Applied and Nginx is Started and Starts on Boot
    - name: Restart and Enable Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes