---

# Depends on community.docker
# Install with: ansible-galaxy collection install community.docker

##################################################################
# Config Crew Ops Team Destroy Portable Web Environment Playbook #
##################################################################

# Usage: ansible-playbook --limit <hosts> destroy_portable_web_env.yml

- name: Destroy Portable Web Environment
  hosts: all
  remote_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    # Delete HTTPD Container
    - name: Remove HTTPD Container
      community.docker.docker_container:
        name: httpd
        state: absent
    # Delete Samba Container
    - name: Remove Samba Container
      community.docker.docker_container:
        name: samba
        state: absent
    # Delete OpenVPN Container
    - name: Remove OpenVPN Container
      community.docker.docker_container:
        name: openvpn
        state: absent
    # Delete OpenVPN Config
    - name: Remove OpenVPN-AS Configs
      ansible.builtin.file:
        path: /vpnconf
        state: absent
    # Delete Web Directory
    - name: Delete Web Directory
      ansible.builtin.file:
        path: /www
        state: absent
    # Close Firewall Ports for Security
    - name: Close Firewall Ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: disabled
      with_items:
        - 943/tcp
        - 943/udp
        - 944/tcp
        - 944/udp
        - 9443/tcp
        - 9443/udp
        - 1194/tcp
        - 1194/udp
        - 139/tcp
        - 139/udp
        - 445/tcp
        - 445/udp
        - 8080/tcp
        - 8080/udp
      vars:
        ansible_python_interpreter: /usr/bin/python
    # Bring Firewall Changes into Effect
    - name: Reload Firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded
