####################################
### LOAD BALANCER INSTALL SCRIPT ###
####################################
#requires ansible.posix
- name: Install nginx repo
  ansible.builtin.yum_repository:
    name: nginx
    description: nginx repo
    baseurl: https://nginx.org/packages/centos/7Server/x86_64/
    gpgcheck: no
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest
- name: open http port
  ansible.posix.firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
- name: open https port
  ansible.posix.firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled
- name: Install nginx.conf
  ansible.builtin.template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Enable/Start nignx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted
- name: Reload nginx
  ansible.builtin.shell:
    cmd: nginx -s reload