---

#######################################################
# Config Crew Ops Team calWeb Version to Dev Playbook #
#######################################################

# Usage: ansible-playbook versionToDev.yml

- name: calWeb Version to Dev
  hosts: dev
  remote_user: root
  vars_prompt:
    - name: version
      prompt: What Explore California Website Version would you like to Install (1.0, 2.0, 3.0, 4.0)?
      private: false

  tasks:

    # This is needed as the private key for the git repo must be on the target host
    - name: Copy Over Git Auth Key
      ansible.builtin.copy:
        src: calWebKey
        dest: /gitauth/
        mode: 0600

    # Install Git
    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present

    # Delete Old Site
    - name: Remove Old Site Files
      ansible.builtin.file:
        path: /var/www/html
        state: absent

    # Clone the requested tag from the git repo onto the web server
    - name: Install Specified Explore California Website Version
      ansible.builtin.git:
        repo: git@github.com:elihopk/calWeb.git
        dest: /var/www/html
        accept_hostkey: true
        key_file: /gitauth/calWebKey
        version: "{{ version }}"

    # Output some useful information for the user
    - ansible.builtin.debug:
        msg: "Explore California Version {{ version }} has been installed. Please verify that the website functions as expected on the following hosts:"
      run_once: true

    - ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
