####################################
### LOAD BALANCER INSTALL SCRIPT ###
####################################
#requires ansible.posix

- name: Confirm Group
  hosts: prod
  remote_user: root
  tasks:
  - name: ping
    ansible.builtin.ping:
- name: Set Up Load Balancer
  hosts: loadbalancer
  remote_user: root
  tasks:
  - name: Install nginx repo
    ansible.builtin.yum_repository:
      name: nginx
      description: nginx repo
      baseurl: https://nginx.org/packages/centos/7Server/x86_64/
      gpgcheck: no
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: latest
  - name: open http port
    ansible.posix.firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled
  - name: Install default.conf
    ansible.builtin.template:
      src: default.conf.j2
      dest: /etc/nginx/conf.d/default.conf

  - name: Enable/Start nignx
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: restarted
