####################################
### LOAD BALANCER INSTALL SCRIPT ###
####################################
---
- name: Set Up Load Balancer
  hosts: loadBalancer
  remote_user: root
  tasks:
  - name: Install python2

  - name: Install nginx
    ansible.builtin.yum_repository:
      name: nginx
      baseurl: https://nginx.org/packages/centos/7Server/x86_64/
      gpgcheck: no
    ansible.builtin.yum:
      name: nginx
      state: latest
  - name: Enable/Start nignx
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: started
