####################################
### LOAD BALANCER INSTALL SCRIPT ###
####################################
---
- name: Set Up Load Balancer
  hosts: loadBalancer
  remote_user: root
  tasks:

  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: Enable/Start nignx
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: started
