####################################
### LOAD BALANCER INSTALL SCRIPT ###
####################################
#requires ansible.posix

- name: Set Up Load Balancer
  hosts: loadbalancer
  remote_user: root
  tasks:
  - name: Install nginx repo
    ansible.builtin.yum_repository:
      name: nginx
      description: nginx repo
      baseurl: https://nginx.org/packages/centos/7Server/x86_64/
      gpgcheck: no
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: latest
  - name: open http port
    ansible.posix.firewalld:
       service: http
       permanent: yes
       state: enabled
  - name: Enable/Start nignx
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: restarted
