---

- name: Uninstall Monitoring Server
  hosts: calWebMon
  remote_user: root
  vars:
    dbname: zabbix
    user: root
    password: administrator
  tasks:
  - name: Uninstall Apache
    ansible.builtin.yum:
      name: httpd
      state: absent
  - name: Uninstall Zabbix Server
    ansible.builtin.yum:
      name: zabbix-server-mysql
      state: absent
  - name: Uninstall Zabbix Web
    ansible.builtin.yum:
      name: zabbix-web
      state: absent
  - name: Uninstall Zabbix Web MySQL
    ansible.builtin.yum:
      name: zabbix-web-mysql
      state: absent
  - name: Uninstall Zabbix Apache Conf
    ansible.builtin.yum:
      name: zabbix-apache-conf
      state: absent
  - name: Uninstall Zabbix SQL Scripts
    ansible.builtin.yum:
      name: zabbix-sql-scripts
      state: absent
  - name: Uninstall Zabbix Agent
    ansible.builtin.yum:
      name: zabbix-agent
      state: absent
  - name: Remove repository
    yum_repository:
      name: zabbix
      state: absent
  - name: Set httpd_can_connect_zabbix flag off
    ansible.posix.seboolean:
      name: httpd_can_connect_zabbix
      state: yes
      persistent: yes
  - name: Drop MySQL Datanase
    mysql_db:
      name: "{{ dbname }}"
      login_user: "{{ user }}"
      state: absent
  - name: Stop MySQL Server
    ignore_errors: yes
    ansible.builtin.systemd:
      name: mysqld
      enabled: no
      state: stopped
  - name: Uninstall Mysql
    ansible.builtin.yum:
      name: mysql
      state: absent
  - name: Uninstall Mysql Server
    ansible.builtin.yum:
      name: mysql-server
      state: absent
  - name: Uninstall PyMySQL
    ansible.builtin.yum:
      name: python3-PyMySQL
      state: absent
  - name: Uninstall zabbix-api
    ansible.builtin.pip:
      name: zabbix-api
      state: absent
  - name: Close HTTP Service
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: disabled
  - name: open monitoring port TCP
    ansible.posix.firewalld:
      port: 10051/tcp
      permanent: yes
      state: disabled
  - name: open monitoring port UDP
    ansible.posix.firewalld:
      port: 10051/udp
      permanent: yes
      state: disabled
  - name: Reload Firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: reloaded
  - name: Remove Zabbix User
    ansible.builtin.user:
      name: zabbix
      state: absent
  - name: Remove Config Files
    ansible.builtin.file:
      path: /etc/zabbix
      state: absent
  - name: Remove Zabbix-Server SEModule
    ansible.builtin.file:
      path: /home/student/zabbix-server.pp
      state: absent