---
#Sets up Zabbix Monitoring Agents
- name: setup zabbix agents
  hosts: monitored
  # ansible_python_interpreter: '/usr/bin/python'
  remote_user: root
  vars:
          monitor_server: '192.168.1.2'
  tasks:
          - name: Ensure Python is Updated
            ansible.builtin.yum:
                    name: python2
                    state: latest
          - name: Ensure Zabbix Agent is Updated
            ansible.builtin.dnf:
                    name: zabbix-agent
                    state: latest
          - name: Write the Zabbix config file
            ansible.builtin.template:
                    src: /home/student/Documents/zabbix_agentd.j2
                    dest: /etc/zabbix/zabbix_agentd.conf
          - name: start Zabbix agent
            ansible.builtin.service:
                    name: zabbix-agent
                    state: restarted
                    enabled: yes
     
