---
# Depends on ansible.posix and commnity.mysql

###############################################################
# Config Crew Ops Team Monitor Server Uninstallation Playbook #
###############################################################

# Usage: ansible-playbook monitor_uninstall.yml

- name: Uninstall Monitoring Server
  hosts: monitorServer
  remote_user: root
  vars:
    dbname: zabbix
    user: root

  tasks:
  # Uninstall All Services except MySQL Related Ones
  - name: Uninstall All Services
    ansible.builtin.yum:
      name: "{{ item }}"
      state: absent
      with_items:
        - httpd
        - zabbix-server-mysql
        - zabbix-web
        - zabbix-web-mysql
        - zabbix-apache-conf
        - zabbix-sql-scripts
        - zabbix-agent

  # Remove the Zabbix yum Repository
  - name: Remove Repository
    ansible.builtin.yum_repository:
      name: zabbix
      state: absent

  # Turn Off Flag Allowing Zabbix Server to Contact localhost Agent
  - name: Set httpd_can_connect_zabbix flag off
    ansible.posix.seboolean:
      name: httpd_can_connect_zabbix
      state: yes
      persistent: yes

  # Drop the Zabbix Database
  - name: Drop MySQL Database
    mysql_db:
      name: "{{ dbname }}"
      login_user: "{{ user }}"
      state: absent

  # Stop then Uninstall MySQL
  - name: Stop MySQL Server
    ignore_errors: yes
    ansible.builtin.systemd:
      name: mysqld
      enabled: no
      state: stopped

  - name: Uninstall Mysql and PyMySQL
    ansible.builtin.yum:
      name: "{{ item }}"
      state: absent
      with_items:
        - mysql
        - python3-PyMySQL

  # Close Unused HTTP Service and Zabbix Ports then Reload Firewalld
  - name: Close HTTP Service
    ansible.posix.firewalld:
      service: http
      permanent: yes
      state: disabled

  - name: Close Zabbix Ports
      ansible.posix.firewalld:
        port: "10051/{{ item }}"
        permanent: yes
        state: disabled
        with_items:
          - tcp
          - udp

  - name: Reload Firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: reloaded

  # - name: Remove Zabbix User
  #   ansible.builtin.user:
  #     name: zabbix
  #     state: absent

  # Remove Old Config Files and SEModule
  - name: Remove Config Files and SEModule
    ansible.builtin.file:
      path: {{ item }}
      state: absent
      with_items:
        - /etc/zabbix
        - /home/student/zabbix-server.pp