---
#Depends on ansible.posix
#Sets up zabbix monitoring server
- name: setup monitor server
  hosts: calWebMon
  remote_user: root
  vars:
          name: zabbix
          user: root
          #password: administrator

  tasks:
          - name: Add repository
            yum_repository:
                    name: zabbix
                    description: Zabbix Repo
                    baseurl: https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/
                    gpgcheck: no
          - name: Set httpd_can_connect_zabbix flag on
            ansible.posix.seboolean:
                    name: httpd_can_connect_zabbix
                    state: yes
                    persistent: yes
          - name: Install zabbix-server-mysql
            ansible.builtin.yum:
                    name: zabbix-server-mysql
                    state: latest
          - name: Explicitly Install zabbix-web
            ansible.builtin.yum:
                    name: zabbix-web
                    state: latest
          - name: Install zabbix-web-mysql
            ansible.builtin.yum:
                    name:  zabbix-web-mysql
                    state: latest
          - name: Install zabbix-apache-conf
            ansible.builtin.yum:
                    name: zabbix-apache-conf
                    state: latest
          - name: Install zabbix-sql-scripts
            ansible.builtin.yum:
                    name: zabbix-sql-scripts
                    state: latest
          - name: Install zabbix-agent
            ansible.builtin.yum:
                    name: zabbix-agent
                    state: latest
          - name: Ensure apache is updated
            ansible.builtin.yum:
                    name: httpd
                    state: latest
          - name: Open HTTP Service
            ansible.posix.firewalld:
                    service: http
                    permanent: yes
                    state: enabled
          - name: Ensure mySQL is updated
            ansible.builtin.yum:
                    name: mysql
                    state: latest
          - name: install mysql-server
            ansible.builtin.yum:
                    name: mysql-server
                    state: latest
          - name: start mySQL Server
            ansible.builtin.systemd:
                    name: mysqld
                    enabled: yes
                    state: restarted
          - name: install PyMySQL
            ansible.builtin.yum:
                    name: python3-PyMySQL
                    state: latest
          - name: Create Zabbix User
            ansible.builtin.user:
                    name: zabbix
                    group: root
          - name: create MySQL database
            mysql_db:
                    name: " {{ name }}"
                    login_user: "{{ user }}"
                    #         login_password: "{{ password }}"
                    state: present
                    collation: utf8_bin
                    encoding: utf8
          - name: Unzip create.sql
            ansible.builtin.shell: gunzip -f /usr/share/doc/zabbix-sql-scripts/mysql/create.sql.gz
          - name: setup mySQL database
            mysql_db:
                    state: import
                    name: "{{ name }}"
                    target: '/usr/share/doc/zabbix-sql-scripts/mysql/create.sql'
          - name: copy config to zabbixserver configuration
            ansible.builtin.template:
                    src: /home/student/Desktop/Config-Crew/Lab2/Ops/zabbix_server54.j2
                    dest: /etc/zabbix/zabbix_server.conf
          - name: copy zabbix-server SELinux module
            ansible.builtin.copy:
                    src: /home/student/Desktop/Config-Crew/Lab2/Ops/zabbix-server.pp
                    dest: /home/student/zabbix-server.pp
          - name: Install zabbix-server SELinux module
            ansible.builtin.shell: semodule -i /home/student/zabbix-server.pp
          - name: start zabbix server
            ansible.builtin.systemd:
                    name: zabbix-server
                    enabled: yes
                    state: restarted
          - name: start zabbix-agent
            ansible.builtin.systemd:
                    name: zabbix-agent
                    enabled: yes
                    state: restarted
          - name: start php-fpm
            ansible.builtin.systemd:
                    name: php-fpm
                    enabled: yes
                    state: restarted
          - name: open monitoring port TCP
            ansible.posix.firewalld:
                    port: 10051/tcp
                    permanent: yes
                    state: enabled
          - name: open monitoring port UDP
            ansible.posix.firewalld:
                    port: 10051/udp
                    permanent: yes
                    state: enabled
          - name: restart apache2
            ansible.builtin.systemd:
                    name: httpd
                    enabled: yes
                    state: restarted
          - name: reload firewalld
            ansible.builtin.systemd:
                    name: firewalld
                    state: reloaded
          - name: Add Zabbix Agent
            local_action:
                    module: community.zabbix.zabbix_host
                    server_url: http://calWebMon/zabbix
                    login_user: Admin
                    login_password: zabbix
                    host_name: calWebProd
                    visible_name: calWebProd
                    interfaces:
                            - type: 1
                              main: 1
                              useip: 1
                              ip: 192.168.1.1
                    link_templates:
                            - Apache by Zabbix agent
                            - HTTP Service
                            - ICMP Ping
                            - Linux by Zabbix agent